#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --partition=gorman-gpu
#SBATCH --time=24:00:00




cd /homes/patil127/scratch/sml/supervised-reptile

conda init bash

# actiate your virtual environment
conda activate sml_project


nvidia-smi

pip install --extra-index-url https://pypi.nvidia.com tensorrt-bindings==8.6.1 tensorrt-libs==8.6.1
pip install tensorflow_gpu==1.15.0


# run your python script
echo "------------------------------------------------------------------------------------------------------"
echo "1-shot 5-way Omniglot."
echo "------------------------------------------------------------------------------------------------------"
python -u run_omniglot.py --shots 1 --inner-batch 10 --inner-iters 5 --meta-step 1 --meta-batch 5 --meta-iters 40000 --eval-batch 5 --eval-iters 50 --learning-rate 0.001 --meta-step-final 0 --train-shots 10 --checkpoint logs/1shot_5way 

echo "------------------------------------------------------------------------------------------------------"
echo "1-shot 5-way Omniglot. Transductive"
echo "------------------------------------------------------------------------------------------------------"
python -u run_omniglot.py --shots 1 --inner-batch 10 --inner-iters 5 --meta-step 1 --meta-batch 5 --meta-iters 40000 --eval-batch 5 --eval-iters 50 --learning-rate 0.001 --meta-step-final 0 --train-shots 10 --checkpoint logs/1shot_5way_trans --transductive 

echo "------------------------------------------------------------------------------------------------------"
echo "1-shot 5-way Omniglot. FOML"
echo "------------------------------------------------------------------------------------------------------"
python -u run_omniglot.py --shots 1 --inner-batch 10 --inner-iters 5 --meta-step 1 --meta-batch 5 --meta-iters 40000 --eval-batch 5 --eval-iters 50 --learning-rate 0.001 --meta-step-final 0 --train-shots 10 --checkpoint logs/1shot_5way_foml --foml

echo "------------------------------------------------------------------------------------------------------"
echo "1-shot 5-way Omniglot. Transductive FOML"
echo "------------------------------------------------------------------------------------------------------"
python -u run_omniglot.py --shots 1 --inner-batch 10 --inner-iters 5 --meta-step 1 --meta-batch 5 --meta-iters 40000 --eval-batch 5 --eval-iters 50 --learning-rate 0.001 --meta-step-final 0 --train-shots 10 --checkpoint logs/1shot_5way_trans_foml --transductive --foml
